<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Austin Thrash">
<meta name="dcterms.date" content="2024-07-26">

<title>Manuscript for a Data Analysis Project: Diabetes Diagnosis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="Manuscript_files/libs/clipboard/clipboard.min.js"></script>
<script src="Manuscript_files/libs/quarto-html/quarto.js"></script>
<script src="Manuscript_files/libs/quarto-html/popper.min.js"></script>
<script src="Manuscript_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Manuscript_files/libs/quarto-html/anchor.min.js"></script>
<link href="Manuscript_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Manuscript_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Manuscript_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Manuscript_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Manuscript_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#summaryabstract" id="toc-summaryabstract" class="nav-link active" data-scroll-target="#summaryabstract"><span class="header-section-number">1</span> Summary/Abstract</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction"><span class="header-section-number">2</span> Introduction</a>
  <ul class="collapse">
  <li><a href="#general-background-information" id="toc-general-background-information" class="nav-link" data-scroll-target="#general-background-information"><span class="header-section-number">2.1</span> General Background Information</a></li>
  <li><a href="#description-of-data-and-data-source" id="toc-description-of-data-and-data-source" class="nav-link" data-scroll-target="#description-of-data-and-data-source"><span class="header-section-number">2.2</span> Description of data and data source</a></li>
  <li><a href="#questionshypotheses-to-be-addressed" id="toc-questionshypotheses-to-be-addressed" class="nav-link" data-scroll-target="#questionshypotheses-to-be-addressed"><span class="header-section-number">2.3</span> Questions/Hypotheses to be addressed</a></li>
  </ul></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods"><span class="header-section-number">3</span> Methods</a>
  <ul class="collapse">
  <li><a href="#data-acquisition" id="toc-data-acquisition" class="nav-link" data-scroll-target="#data-acquisition"><span class="header-section-number">3.1</span> Data acquisition</a>
  <ul class="collapse">
  <li><a href="#outcome-of-interest" id="toc-outcome-of-interest" class="nav-link" data-scroll-target="#outcome-of-interest"><span class="header-section-number">3.1.1</span> Outcome of Interest</a></li>
  <li><a href="#what-if-any-specific-predictors-will-you-focus-on" id="toc-what-if-any-specific-predictors-will-you-focus-on" class="nav-link" data-scroll-target="#what-if-any-specific-predictors-will-you-focus-on"><span class="header-section-number">3.1.2</span> What (if any) specific predictors will you focus on?</a></li>
  <li><a href="#what-relationspatterns-are-you-looking-for-in-the-data" id="toc-what-relationspatterns-are-you-looking-for-in-the-data" class="nav-link" data-scroll-target="#what-relationspatterns-are-you-looking-for-in-the-data"><span class="header-section-number">3.1.3</span> What relations/patterns are you looking for in the data?</a></li>
  </ul></li>
  <li><a href="#data-import-and-cleaning" id="toc-data-import-and-cleaning" class="nav-link" data-scroll-target="#data-import-and-cleaning"><span class="header-section-number">3.2</span> Data import and cleaning</a></li>
  <li><a href="#statistical-analysis-method" id="toc-statistical-analysis-method" class="nav-link" data-scroll-target="#statistical-analysis-method"><span class="header-section-number">3.3</span> Statistical analysis method</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><span class="header-section-number">4</span> Results</a>
  <ul class="collapse">
  <li><a href="#exploratorydescriptive-analysis" id="toc-exploratorydescriptive-analysis" class="nav-link" data-scroll-target="#exploratorydescriptive-analysis"><span class="header-section-number">4.1</span> Exploratory/Descriptive analysis</a>
  <ul class="collapse">
  <li><a href="#distribution-of-all-variables" id="toc-distribution-of-all-variables" class="nav-link" data-scroll-target="#distribution-of-all-variables"><span class="header-section-number">4.1.1</span> Distribution of all variables</a></li>
  <li><a href="#correlation-matrix" id="toc-correlation-matrix" class="nav-link" data-scroll-target="#correlation-matrix"><span class="header-section-number">4.1.2</span> Correlation Matrix</a></li>
  <li><a href="#feature-importance---linear-regression" id="toc-feature-importance---linear-regression" class="nav-link" data-scroll-target="#feature-importance---linear-regression"><span class="header-section-number">4.1.3</span> Feature Importance - Linear Regression</a></li>
  <li><a href="#feature-importance---random-forest" id="toc-feature-importance---random-forest" class="nav-link" data-scroll-target="#feature-importance---random-forest"><span class="header-section-number">4.1.4</span> Feature Importance - Random Forest</a></li>
  </ul></li>
  <li><a href="#basic-statistical-analysis" id="toc-basic-statistical-analysis" class="nav-link" data-scroll-target="#basic-statistical-analysis"><span class="header-section-number">4.2</span> Basic statistical analysis</a>
  <ul class="collapse">
  <li><a href="#methods-1" id="toc-methods-1" class="nav-link" data-scroll-target="#methods-1"><span class="header-section-number">4.2.1</span> Methods</a></li>
  <li><a href="#preparing-the-data" id="toc-preparing-the-data" class="nav-link" data-scroll-target="#preparing-the-data"><span class="header-section-number">4.2.2</span> Preparing the data</a></li>
  <li><a href="#results-1" id="toc-results-1" class="nav-link" data-scroll-target="#results-1"><span class="header-section-number">4.2.3</span> Results</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion"><span class="header-section-number">5</span> Discussion</a>
  <ul class="collapse">
  <li><a href="#summary-and-interpretation" id="toc-summary-and-interpretation" class="nav-link" data-scroll-target="#summary-and-interpretation"><span class="header-section-number">5.1</span> Summary and Interpretation</a></li>
  <li><a href="#strengths-and-limitations" id="toc-strengths-and-limitations" class="nav-link" data-scroll-target="#strengths-and-limitations"><span class="header-section-number">5.2</span> Strengths and Limitations</a></li>
  <li><a href="#conclusions" id="toc-conclusions" class="nav-link" data-scroll-target="#conclusions"><span class="header-section-number">5.3</span> Conclusions</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">6</span> References</a></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Manuscript for a Data Analysis Project: Diabetes Diagnosis</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Austin Thrash </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 26, 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="summaryabstract" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Summary/Abstract</h1>
<p>Diabetes is a chronic condition that affects millions of people worldwide, characterized by high blood glucose levels and serious complications if not managed properly. This study aims to identify key health indicators predicting the likelihood of an individual being diagnosed with diabetes using a dataset from the UC Irvine Machine Learning Repository, containing over 250,000 instances and 21 features. Three models were utilized: logistic regression, random forest, and K-nearest neighbors (KNN). The analysis revealed that BMI, high blood pressure, heart disease or attack history, and heavy alcohol consumption were significant predictors of diabetes. Logistic regression and KNN models demonstrated reasonable accuracy, while the random forest model required refinement. The study highlights the importance of these health indicators and suggests further data processing and model tuning for improved predictive performance.</p>
<div style="page-break-after: always;"></div>
</section>
<section id="introduction" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Introduction</h1>
<section id="general-background-information" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="general-background-information"><span class="header-section-number">2.1</span> General Background Information</h2>
<p>“Diabetes can lead to severe, and in some cases, life-threatening complications.” <span class="citation" data-cites="ADA">(<a href="#ref-ADA" role="doc-biblioref"><em>Warning symptoms</em>, 2024</a>)</span>. Diabetes is a major cause of blindness, kidney failure, heart attacks, stroke, and lower limb amputation. Managing diabetes and its complications places a significant burden on healthcare systems worldwide. Early diagnosis and management are crucial to prevent adverse health outcomes. Several studies have identified various risk factors associated with diabetes, including age, BMI, physical activity, and dietary habits.</p>
</section>
<section id="description-of-data-and-data-source" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="description-of-data-and-data-source"><span class="header-section-number">2.2</span> Description of data and data source</h2>
<p>This dataset comes from UC Irvine Machine Learning Repository. This data has been gathered and processed from the CDCs website in 2014. This dataset includes over 250,000 instances (observations) and 21 features, ranging from personal information (income/education) to health history (drinking/smoking/physical health). Bellow are the features and there respective descriptions</p>
<table class="table">
<colgroup>
<col style="width: 29%">
<col style="width: 70%">
</colgroup>
<thead>
<tr class="header">
<th>Feature</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ID</td>
<td>Patient ID</td>
</tr>
<tr class="even">
<td>Diabetes_binary</td>
<td>0 = no diabetes 1 = prediabetes or diabetes</td>
</tr>
<tr class="odd">
<td>HighBP</td>
<td>0 = no high BP 1 = high BP</td>
</tr>
<tr class="even">
<td>HighChol</td>
<td>0 = no high cholesterol 1 = high cholesterol</td>
</tr>
<tr class="odd">
<td>CholCheck</td>
<td>0 = no cholesterol check in 5 years 1 = yes cholesterol check in 5 years</td>
</tr>
<tr class="even">
<td>BMI</td>
<td>Body Mass Index</td>
</tr>
<tr class="odd">
<td>Smoker</td>
<td>Have you smoked at least 100 cigarettes in your entire life? [Note: 5 packs = 100 cigarettes] 0 = no 1 = yes</td>
</tr>
<tr class="even">
<td>Stoke</td>
<td>(Ever told) you had a stroke. 0 = no 1 = yes</td>
</tr>
<tr class="odd">
<td>HeartDiseaseorAttack</td>
<td>coronary heart disease (CHD) or myocardial infarction (MI) 0 = no 1 = yes</td>
</tr>
<tr class="even">
<td>PhysActivity</td>
<td>physical activity in past 30 days - not including job 0 = no 1 = yes</td>
</tr>
<tr class="odd">
<td>Fruits</td>
<td>Consume Fruit 1 or more times per day 0 = no 1 = yes</td>
</tr>
<tr class="even">
<td>Veggies</td>
<td>Consume Vegetables 1 or more times per day 0 = no 1 = yes</td>
</tr>
<tr class="odd">
<td>HvyAlchoholConsump</td>
<td>Heavy drinkers (adult men having more than 14 drinks per week and adult women having more than 7 drinks per week) 0 = no 1 = yes</td>
</tr>
<tr class="even">
<td>AnyHealthcare</td>
<td>Have any kind of health care coverage, including health insurance, prepaid plans such as HMO, etc. 0 = no 1 = yes</td>
</tr>
<tr class="odd">
<td>NoDocbcCost</td>
<td>Was there a time in the past 12 months when you needed to see a doctor but could not because of cost? 0 = no 1 = yes</td>
</tr>
<tr class="even">
<td>GenHlth</td>
<td>Would you say that in general your health is: scale 1-5 1 = excellent 2 = very good 3 = good 4 = fair 5 = poor</td>
</tr>
<tr class="odd">
<td>MentHlth</td>
<td>Now thinking about your mental health, which includes stress, depression, and problems with emotions, for how many days during the past 30 days was your mental health not good? scale 1-30 days</td>
</tr>
<tr class="even">
<td>PhysHlth</td>
<td>Now thinking about your physical health, which includes physical illness and injury, for how many days during the past 30 days was your physical health not good? scale 1-30 days</td>
</tr>
<tr class="odd">
<td>DiffWalk</td>
<td>Do you have serious difficulty walking or climbing stairs? 0 = no 1 = yes</td>
</tr>
<tr class="even">
<td>Sex</td>
<td>0 = female 1 = male</td>
</tr>
<tr class="odd">
<td>Age</td>
<td>13-level age category (_AGEG5YR see codebook) 1 = 18-24 9 = 60-64 13 = 80 or older</td>
</tr>
<tr class="even">
<td>Education</td>
<td>Education level (EDUCA see codebook) scale 1-6 1 = Never attended school or only kindergarten 2 = Grades 1 through 8 (Elementary) 3 = Grades 9 through 11 (Some high school) 4 = Grade 12 or GED (High school graduate) 5 = College 1 year to 3 years (Some college or technical school) 6 = College 4 years or more (College graduate)</td>
</tr>
<tr class="odd">
<td>Income</td>
<td>Income scale (INCOME2 see codebook) scale 1-8 1 = less than $10,000 5 = less than $35,000 8 = $75,000 or more</td>
</tr>
</tbody>
</table>
<p><a href="https://archive.ics.uci.edu/dataset/891/cdc+diabetes+health+indicators" class="uri">https://archive.ics.uci.edu/dataset/891/cdc+diabetes+health+indicators</a></p>
</section>
<section id="questionshypotheses-to-be-addressed" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="questionshypotheses-to-be-addressed"><span class="header-section-number">2.3</span> Questions/Hypotheses to be addressed</h2>
<p>“What are the key health indicators that predict the likelihood of an individual being diagnosed with diabetes?” Specifically, identifying which factors are most strongly associated with diabetes prevalence in the population.</p>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="methods" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Methods</h1>
<p>The main question I would like to answer with this project is “What are the key health indicators that predict the likelihood of an individual being diagnosed with diabetes?”.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="data-acquisition" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="data-acquisition"><span class="header-section-number">3.1</span> Data acquisition</h2>
<p>This data comes from CDC and will be sampled during analysis.</p>
<section id="outcome-of-interest" class="level3" data-number="3.1.1">
<h3 data-number="3.1.1" class="anchored" data-anchor-id="outcome-of-interest"><span class="header-section-number">3.1.1</span> Outcome of Interest</h3>
<p>The primary outcome of interest will be whether an individual has been diagnosed with diabetes or not. This outcome will be represented as a binary variable where 1 indicates a diabetes diagnosis and 0 indicates no diabetes.</p>
</section>
<section id="what-if-any-specific-predictors-will-you-focus-on" class="level3" data-number="3.1.2">
<h3 data-number="3.1.2" class="anchored" data-anchor-id="what-if-any-specific-predictors-will-you-focus-on"><span class="header-section-number">3.1.2</span> What (if any) specific predictors will you focus on?</h3>
<p>The specific predictors I will focus on are age, gender, BMI, consumption of fruits and vegetables, and frequency of exercise. Although these are the main predictors I will focus on, I’ll also use data analytic techniques to identify which predictors are of importance or have relationships with the response variable.</p>
</section>
<section id="what-relationspatterns-are-you-looking-for-in-the-data" class="level3" data-number="3.1.3">
<h3 data-number="3.1.3" class="anchored" data-anchor-id="what-relationspatterns-are-you-looking-for-in-the-data"><span class="header-section-number">3.1.3</span> What relations/patterns are you looking for in the data?</h3>
<p>I will look for patterns ad relationships between the predictors and the outcome of diabetes diagnosis. More specifically, I will analyze correlations between individual predictors and the response variable, interaction effects between predictors and the response variable, and predictive models such as logistic regression, decision trees, and machine learning classifiers.</p>
</section>
</section>
<section id="data-import-and-cleaning" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="data-import-and-cleaning"><span class="header-section-number">3.2</span> Data import and cleaning</h2>
<p>Not much occurs during the cleaning stage as the dataset was processed and cleaned prior. The only modifications made to the dataset was removing the ‘ID’ column as it is not useful for this analysis. Once the data was imported, it was only a matter of converting categorical variables to factors so they would function properly. One-hot encoding was implemented, but only for the multinomial logistic regression.</p>
</section>
<section id="statistical-analysis-method" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="statistical-analysis-method"><span class="header-section-number">3.3</span> Statistical analysis method</h2>
<p>For my analysis, I will first look at the distributions of each variable to identify if the dataset is balanced and outliers. I do not think any data cleaning will need to be done as that was completed when the data was collected from the CDC’s website. Next, I will create a correlation matrix to view the correlations between each predictor and the response variable. After viewing the correlations, I will then use simple linear regression and random forest models to identify variables of importance, these variables will be noted and used later during the modeling phase. I will utilize cross validation during the modeling phase. This section will be filled out more once we are further into the class and have discussed more approaches/methods.</p>
<section id="logistic-regression" class="level4" data-number="3.3.0.1">
<h4 data-number="3.3.0.1" class="anchored" data-anchor-id="logistic-regression"><span class="header-section-number">3.3.0.1</span> Logistic Regression</h4>
<p>Logistic regression will be used to model the relationship between the binary outcome variable and the predictors. This method will help in understanding the influence of each predictor on the likelihood of diabetes diagnosis.</p>
</section>
<section id="random-forest" class="level4" data-number="3.3.0.2">
<h4 data-number="3.3.0.2" class="anchored" data-anchor-id="random-forest"><span class="header-section-number">3.3.0.2</span> Random Forest</h4>
<p>Random forest, an ensemble learning method, will be used to improve the accuracy and robustness of predictions. It will help in identifying the importance of each predictor in determining the diabetes diagnosis.</p>
</section>
<section id="k-nearest-neighbors-knn" class="level4" data-number="3.3.0.3">
<h4 data-number="3.3.0.3" class="anchored" data-anchor-id="k-nearest-neighbors-knn"><span class="header-section-number">3.3.0.3</span> K-Nearest Neighbors (KNN)</h4>
<p>KNN will be used as a non-parametric method to classify individuals based on the closest training examples in the feature space. This will provide insights into the influence of neighborhood-based predictions on diabetes diagnosis.</p>
<p>For my model selection, I referenced ISLR2. <span class="citation" data-cites="ISLR">(<a href="#ref-ISLR" role="doc-biblioref">Gareth James, 2023</a>)</span></p>
<div style="page-break-after: always;"></div>
</section>
</section>
</section>
<section id="results" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Results</h1>
<section id="exploratorydescriptive-analysis" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="exploratorydescriptive-analysis"><span class="header-section-number">4.1</span> Exploratory/Descriptive analysis</h2>
<section id="distribution-of-all-variables" class="level3" data-number="4.1.1">
<h3 data-number="4.1.1" class="anchored" data-anchor-id="distribution-of-all-variables"><span class="header-section-number">4.1.1</span> Distribution of all variables</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="fu">here</span>(<span class="st">"results"</span>,<span class="st">"figures"</span>,<span class="st">"variable-distributions.png"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="../../results/figures/variable-distributions.png" class="img-fluid" width="3000"></p>
</div>
</div>
</section>
<section id="correlation-matrix" class="level3" data-number="4.1.2">
<h3 data-number="4.1.2" class="anchored" data-anchor-id="correlation-matrix"><span class="header-section-number">4.1.2</span> Correlation Matrix</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="fu">here</span>(<span class="st">"results"</span>,<span class="st">"figures"</span>,<span class="st">"correlation_matrix.png"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="../../results/figures/correlation_matrix.png" class="img-fluid" width="400"></p>
</div>
</div>
</section>
<section id="feature-importance---linear-regression" class="level3" data-number="4.1.3">
<h3 data-number="4.1.3" class="anchored" data-anchor-id="feature-importance---linear-regression"><span class="header-section-number">4.1.3</span> Feature Importance - Linear Regression</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="fu">here</span>(<span class="st">"results"</span>,<span class="st">"figures"</span>,<span class="st">"importance_table.png"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="../../results/figures/importance_table.png" class="img-fluid" width="213"></p>
</div>
</div>
</section>
<section id="feature-importance---random-forest" class="level3" data-number="4.1.4">
<h3 data-number="4.1.4" class="anchored" data-anchor-id="feature-importance---random-forest"><span class="header-section-number">4.1.4</span> Feature Importance - Random Forest</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="fu">here</span>(<span class="st">"results"</span>,<span class="st">"figures"</span>,<span class="st">"variable_importance.png"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="../../results/figures/variable_importance.png" class="img-fluid" width="500"></p>
</div>
</div>
<p>Overall, the variables do not show much correlation with one another, however I have a feeling that I may need to do more data processing, i.e.&nbsp;making categorical variables into factors and removing them from the correlation matrix. I decided to include some distributions of variables that I found to be interesting, such as BMI, Age, PhysHlth, and Smoker. After running both a linear and random forest model to determine the most important features, it looks as if BMI, HighBP, HeartDiseaseorAttack, and HvyAlchoholConsump are the most important features to include in the models.</p>
</section>
</section>
<section id="basic-statistical-analysis" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="basic-statistical-analysis"><span class="header-section-number">4.2</span> Basic statistical analysis</h2>
<section id="methods-1" class="level3" data-number="4.2.1">
<h3 data-number="4.2.1" class="anchored" data-anchor-id="methods-1"><span class="header-section-number">4.2.1</span> Methods</h3>
<p>After processing and exploring the data, it was discovered that a majority of the features in this dataset are categorical. Therefore, we will be making use of models that are more rigorous to our situation, such as random forest and KNN. However before trying those models, we will first do a simple multinomial logistic regression. Why multinomial? That is because our response variable is not binary, it has three levels to it; typically, logistic regression is used for binary classification. After creating models with all features included, we will go on to look at models with features that fit our importance criteria (i.e.&nbsp;look at the models results when using the most important features).</p>
</section>
<section id="preparing-the-data" class="level3" data-number="4.2.2">
<h3 data-number="4.2.2" class="anchored" data-anchor-id="preparing-the-data"><span class="header-section-number">4.2.2</span> Preparing the data</h3>
<p>For some of the models, mainly multinomial logistic regression, we need to further process our data. The method we will use is known as one-hot encoding. One-hot encoding is a process of converting categorical variables into a binary (0 or 1) format where each category becomes a new binary column. We need to do this because most machine learning algorithms require numerical input and cannot handle categorical data directly, so formatting this data in a different manner will provide us with better results.</p>
</section>
<section id="results-1" class="level3" data-number="4.2.3">
<h3 data-number="4.2.3" class="anchored" data-anchor-id="results-1"><span class="header-section-number">4.2.3</span> Results</h3>
<section id="multinomial-logistic-regression---all-features" class="level4" data-number="4.2.3.1">
<h4 data-number="4.2.3.1" class="anchored" data-anchor-id="multinomial-logistic-regression---all-features"><span class="header-section-number">4.2.3.1</span> Multinomial Logistic Regression - All Features</h4>
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction    X0    X1    X2
        X0 21075   398  2891
        X1     3     1     1
        X2   477    32   622

Overall Statistics
                                          
               Accuracy : 0.8509          
                 95% CI : (0.8465, 0.8553)
    No Information Rate : 0.8453          
    P-Value [Acc &gt; NIR] : 0.006606        
                                          
                  Kappa : 0.1995          
                                          
 Mcnemar's Test P-Value : &lt; 2.2e-16       

Statistics by Class:

                     Class: X0 Class: X1 Class: X2
Sensitivity             0.9777 2.320e-03   0.17701
Specificity             0.1663 9.998e-01   0.97685
Pos Pred Value          0.8650 2.000e-01   0.54996
Neg Pred Value          0.5775 9.831e-01   0.88132
Prevalence              0.8453 1.690e-02   0.13780
Detection Rate          0.8265 3.922e-05   0.02439
Detection Prevalence    0.9555 1.961e-04   0.04435
Balanced Accuracy       0.5720 5.011e-01   0.57693</code></pre>
<p>The logistic regression model was applied to the dataset to analyze the relationship between the binary outcome variable (diabetes diagnosis) and the predictors. The model achieved an accuracy of 85.09%. However, the model showed that the target variable might not be balanced, indicating that further data processing might be necessary.</p>
</section>
<section id="random-forest---all-features" class="level4" data-number="4.2.3.2">
<h4 data-number="4.2.3.2" class="anchored" data-anchor-id="random-forest---all-features"><span class="header-section-number">4.2.3.2</span> Random Forest - All Features</h4>
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction    X0    X1    X2
        X0 21555   431  3514
        X1     0     0     0
        X2     0     0     0

Overall Statistics
                                          
               Accuracy : 0.8453          
                 95% CI : (0.8408, 0.8497)
    No Information Rate : 0.8453          
    P-Value [Acc &gt; NIR] : 0.5042          
                                          
                  Kappa : 0               
                                          
 Mcnemar's Test P-Value : NA              

Statistics by Class:

                     Class: X0 Class: X1 Class: X2
Sensitivity             1.0000    0.0000    0.0000
Specificity             0.0000    1.0000    1.0000
Pos Pred Value          0.8453       NaN       NaN
Neg Pred Value             NaN    0.9831    0.8622
Prevalence              0.8453    0.0169    0.1378
Detection Rate          0.8453    0.0000    0.0000
Detection Prevalence    1.0000    0.0000    0.0000
Balanced Accuracy       0.5000    0.5000    0.5000</code></pre>
<p>The random forest model was applied to the dataset to improve the accuracy and robustness of predictions. The model, however, only predicted the class ‘0’, likely due to an error in model setup. This resulted in an accuracy that was not applicable, indicating the need for further refinement of the model.</p>
</section>
<section id="knn---all-features" class="level4" data-number="4.2.3.3">
<h4 data-number="4.2.3.3" class="anchored" data-anchor-id="knn---all-features"><span class="header-section-number">4.2.3.3</span> KNN - All Features</h4>
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction    X0    X1    X2
        X0 21270   415  2975
        X1     0     0     0
        X2   285    16   539

Overall Statistics
                                          
               Accuracy : 0.8553          
                 95% CI : (0.8509, 0.8596)
    No Information Rate : 0.8453          
    P-Value [Acc &gt; NIR] : 4.769e-06       
                                          
                  Kappa : 0.1869          
                                          
 Mcnemar's Test P-Value : &lt; 2.2e-16       

Statistics by Class:

                     Class: X0 Class: X1 Class: X2
Sensitivity             0.9868    0.0000   0.15339
Specificity             0.1407    1.0000   0.98631
Pos Pred Value          0.8625       NaN   0.64167
Neg Pred Value          0.6607    0.9831   0.87936
Prevalence              0.8453    0.0169   0.13780
Detection Rate          0.8341    0.0000   0.02114
Detection Prevalence    0.9671    0.0000   0.03294
Balanced Accuracy       0.5637    0.5000   0.56985</code></pre>
<p>The KNN model was applied to the dataset and achieved an accuracy of 85.53%. The model’s sensitivity and specificity values indicated that it performed reasonably well, but there was room for improvement, particularly in predicting minority classes.</p>
</section>
<section id="model-comparisons" class="level4" data-number="4.2.3.4">
<h4 data-number="4.2.3.4" class="anchored" data-anchor-id="model-comparisons"><span class="header-section-number">4.2.3.4</span> Model Comparisons</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="fu">here</span>(<span class="st">"results"</span>,<span class="st">"figures"</span>,<span class="st">"model_accuracy_comparison.png"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="../../results/figures/model_accuracy_comparison.png" class="img-fluid" width="1050"></p>
</div>
</div>
<div style="page-break-after: always;"></div>
</section>
</section>
</section>
</section>
<section id="discussion" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Discussion</h1>
<section id="summary-and-interpretation" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="summary-and-interpretation"><span class="header-section-number">5.1</span> Summary and Interpretation</h2>
<p>The analysis revealed that BMI, HighBP, HeartDiseaseorAttack, and HvyAlchoholConsump were significant predictors of diabetes diagnosis. Logistic regression and KNN models showed reasonable accuracy, while the random forest model required further refinement. These findings highlight the importance of these health indicators in predicting diabetes and suggest that further data processing and model tuning could improve predictive performance.</p>
</section>
<section id="strengths-and-limitations" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="strengths-and-limitations"><span class="header-section-number">5.2</span> Strengths and Limitations</h2>
<ul>
<li><p><strong>Imbalanced Dataset</strong>: The dataset was imbalanced, which affected the model’s performance, particularly in predicting minority classes.</p></li>
<li><p><strong>Categorical Data Handling</strong>: The handling of categorical variables posed challenges, especially for models like logistic regression and random forest.</p></li>
<li><p><strong>Model Setup Errors</strong>: The random forest model’s performance indicated potential errors in model setup, necessitating further refinement.</p></li>
</ul>
</section>
<section id="conclusions" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="conclusions"><span class="header-section-number">5.3</span> Conclusions</h2>
<p>The study identified key health indicators that are strongly associated with diabetes diagnosis. Logistic regression and KNN models provided reasonable predictive accuracy, while the random forest model required further refinement. These findings underscore the need for balanced datasets and appropriate handling of categorical variables to improve model performance.</p>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="references" class="level1 unnumbered" data-number="6">


</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">6 References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-line-spacing="2" role="list">
<div id="ref-ISLR" class="csl-entry" role="listitem">
Gareth James, T. H., Daniela Witten. (2023). <em>An introduction to statistical learning</em> (2nd ed.).
</div>
<div id="ref-ADA" class="csl-entry" role="listitem">
<em>Warning symptoms</em>. (2024). Retrieved from <a href="https://diabetes.org/about-diabetes/warning-signs-symptoms">https://diabetes.org/about-diabetes/warning-signs-symptoms</a>
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>